export const MESSAGE_FONT = "Yu Gothic UI";
export const MESSAGE_FONT_SIZE_PX = 32;

export const SOUND_SHOT_PLAYER = 'SOUND_SHOT_PLAYER';
export const SOUND_SHOT_ENEMY = 'SOUND_SHOT_ENEMY';
export const SOUND_EXPLOSION_PLAYER = 'SOUND_EXPLOSION_PLAYER';
export const SOUND_EXPLOSION_ENEMY = 'SOUND_EXPLOSION_ENEMY';

export const VISIBLE_DISTANCE_OBSTACLES = 2000.0;
export const VISIBLE_DISTANCE_ENEMIES = 1000.0;

export const Z_LIMIT = -2000.0;
